// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rljgxjdcxpwgfiaexpmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsamd4amRjeHB3Z2ZpYWV4cG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mzk1NzUsImV4cCI6MjA2ODUxNTU3NX0.fG0TEXENLkJmaSYvWDMxJN_t6n3IBrw0saMhp-B9I24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});